version: '2.1'
services:
  pals-pg:
      image: postgres:15-alpine
      container_name: pals-pg
      ports:
        - '${PALS_LIB_POSTGRES_IP:-127.0.0.1}:${PALS_LIB_POSTGRES_PORT:-54321}:5432'
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
